### ISSUE TITLE
If there aren't 10 items to show then hide the episode prefix 'E -'

### ISSUE THREAD

**Issue by AmbrosiaDevelopments** [Duwaynef/Sonarr-RainMeter#1]
I'm not sure if this is a bug and relates to the duplicating of the first entry 'USS Callister' but without the '1' but the skin also still shows 'E -' when there are less than 10 episodes lined up. Unsure how you want bug reports so here's a screen shot.

![untitled](https://user-images.githubusercontent.com/17378796/34260723-e7c03e84-e6ba-11e7-90b1-a2c7d31faa76.png)

**Comment by Duwaynef** [comment]
yeah, the downfall of rainmeter is that you manually program how many items to show...

so if you want 5 total you have to remove the code for the other 5... kinda silly.

but you can't say for each show up to 10 display x data.

**Comment by Duwaynef** [comment]
right now rainmeter goes forward for a long time so once you have more shows in your sonarr it will fill up.

so you would delete each of these for how many you want to remove.

`[Banner10]
Meter=IMAGE
MeasureName=sonarr_next_banner_url10
X=#BannerX#
Y=#BannerY#
W=#BannerW#
H=#BannerH#
LeftMouseDownAction=!execute [#HOST_PORT#/series/[&sonarr_next_show_url10]]
DynamicVariables=1
[Banner10-SHOWNAME]
Meter=STRING
FontColor=#FontColor#
FontSize=#FontSize#
FontFace=#FontName#
FontEffectColor=#BlueColor#
StringEffect=#BlueBorder#
X=#ShowNameX#
Y=#ShowNameY#
MeasureName=sonarr_next_show_name10
LeftMouseDownAction=!execute [#HOST_PORT#/series/[&sonarr_next_show_url10]]
AntiAlias=1
[Banner10-EPNAME]
Meter=STRING
FontColor=#FontColor#
FontSize=#FontSize#
FontFace=#FontName4#
AntiAlias=1
X=#EpNameX#
Y=#EpNameY#
MeasureName=sonarr_next_episodes_name1
MeasureName2=sonarr_next_episode_no10
MeasureName3=sonarr_downloaded10
Text="E%2 - %1 %3"
Hidden=0
[Banner10-seasonBG]
Meter=IMAGE
X=#seasonBGX#
Y=#seasonBGY#
AntiAlias=1
ImageName=season.png
[Banner10-episodeBG]
Meter=IMAGE
X=#EpisodeBGX#
Y=#EpisodeBGY#
AntiAlias=1
ImageName=episode.png
[Banner10-seasonDATE]
Meter=STRING
FontColor=#FontColor#
FontSize=#FontSize#
FontFace=#FontName#
FontEffectColor=#BlueColor#
X=#seasonDateX#
Y=#seasonDateY#
MeasureName=sonarr_next_episode_airdate10
AntiAlias=1
[Banner10-seasonTIME]
Meter=STRING
FontColor=#FontColor#
FontSize=#FontSize#
FontFace=#FontName#
FontEffectColor=#BlueColor#
;StringEffect=#BlueBorder#
X=#seasonTimeX#
Y=#seasonTimeY#
MeasureName=sonarr_next_episode_airtime10
AntiAlias=1

;###################################################################`
